
# This CI will build openmc with dagmc using the development branches of both

name: CI

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: continuumio/miniconda3:4.12.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install dependencies
        run: |
          apt-get --allow-releaseinfo-change update
          apt-get update -y
          apt-get upgrade -y
          conda config --add channels conda-forge
          conda config --set channel_priority strict
          conda install mamba -y
          mamba install gxx -y
          mamba install cmake -y
          mamba install make -y
          mamba install binutils -y
          mamba install -c conda-forge dagmc=3.2.2 -y
          # git clone --single-branch --branch develop --depth 1 https://github.com/openmc-dev/openmc.git
          # this branch is upto date with develop, but contains material.from_library
          git clone --single-branch --branch adding_material_from_library --depth 1 https://github.com/shimwell/openmc.git
          cd openmc
          mkdir build
          cd build
          cmake -Doptimize=on -Ddagmc=ON -DHDF5_PREFER_PARALLEL=off ..
          make -j2
          make -j2 install
          cd ..
          pip install .
          pip install openmc_data_downloader
          openmc_data_downloader -l TENDL-2019 -e H C O Na Mg Al Si K Ca Fe
        env:
          OPENMC_CROSS_SECTIONS : /__w/openmc_diff/openmc_diff/openmc/cross_sections.xml

      - name: Run simulation 
        run: |
          python spectra_tally_openmc_0_13_1.py

